version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/distro"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "library/golang"
        versions: ["*rc*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
