name: Distro

on:
  workflow_dispatch:
  push:

env:
  TAG_NAME: ${{ format('wslvpnkit:{0}-{1}', github.sha, github.run_number) }}
  RUN_URL: ${{ format('{0}/{1}/actions/runs/{2}/attempts/{3}', github.server_url, github.repository, github.run_id, github.run_attempt) }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: docker/setup-docker-action@v5
      with:
        daemon-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          }
    - uses: docker/setup-qemu-action@v4
    - uses: docker/setup-buildx-action@v4
    - uses: actions/checkout@v7

    - uses: docker/build-push-action@v7
      with:
        context: .
        file: ./distro/alpine.dockerfile
        platforms: linux/arm64,linux/amd64
        push: false
        load: true
        tags: ${{ env.TAG_NAME }}
        build-args: |
          REF=${{ env.RUN_URL }}
          VERSION=${GITHUB_REF#refs/tags/}

    - name: export amd64
      run: |
        CONTAINER_ID=$(docker create --platform linux/amd64 ${{ env.TAG_NAME }})
        docker export $CONTAINER_ID | gzip > wsl-vpnkit-amd64.wsl
        sha256sum wsl-vpnkit-amd64.wsl | tee wsl-vpnkit-amd64.wsl.sha256
        ls -la wsl-vpnkit-amd64.wsl
    - name: export arm64
      run: |
        CONTAINER_ID=$(docker create --platform linux/arm64 ${{ env.TAG_NAME }})
        docker export $CONTAINER_ID | gzip > wsl-vpnkit-arm64.wsl
        sha256sum wsl-vpnkit-arm64.wsl | tee wsl-vpnkit-arm64.wsl.sha256
        ls -la wsl-vpnkit-arm64.wsl

    - uses: actions/upload-artifact@v7
      with:
        path: |
          wsl-vpnkit-amd64.wsl
          wsl-vpnkit-amd64.wsl.sha256
          wsl-vpnkit-arm64.wsl
          wsl-vpnkit-arm64.wsl.sha256

    - uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        token: ${{ secrets.GH_TOKEN }}
        prerelease: true
        draft: true
        files: |
          wsl-vpnkit-amd64.wsl
          wsl-vpnkit-amd64.wsl.sha256
          wsl-vpnkit-arm64.wsl
          wsl-vpnkit-arm64.wsl.sha256
